apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: dot-db
  name: dot-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dot-db
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: dot-db
    spec:
      containers:
      - image: niharika0606/db01:latest
        name: db01
        resources: {}
status: {}
