apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: dot-net
  name: dot-net
spec:
  ports:
  - name: 80-8080
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: dot-net
  type: LoadBalancer
status:
  loadBalancer: {}
