name: ci
on:
  push:
    branches:
      - 'master'
    tags: 'v1.0.0'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Publish Helm charts
        uses: Harish0717/Quexy@master
        with:
          token: ${{ secrets.TOKEN_GITHUB }}  
      - name: Checkout
        uses: actions/checkout@v2 
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context:  amd64/hello-world/.
          push: true 
          tags: harish0717/dot-net:v1            
        
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2 
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context:  amd64/hello-world/.
          push: true 
          tags: harish0717/dot-net:v1            
