name: release
on:
  push:
    tags: '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish Helm charts
        uses: Harish0717/helm-gh-pages@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
